DROP TABLE IF EXISTS PASIEN;

USE databaseKelompok4;

CREATE TABLE pasien (
	[ID_PASIEN]	VARCHAR(100)	PRIMARY KEY,
	[NAMA_PASIEN]	VARCHAR(100)	NOT NULL,
	[KELUHAN]	VARCHAR(50)	NOT NULL,
	/*
	[TANGGAL_LAHIR]		DATE			NOT NULL,
	[ID_DOKTER]		VARCHAR(10)		FOREIGN KEY(),
	[ID_OBAT]		VARCHAR(10)		FOREIGN KEY(),
	[TANGGAL_PERIKSA]	DATE			NOT NULL,
	*/
);

INSERT INTO PASIEN (ID_PASIEN, NAMA_PASIEN, KELUHAN)
VALUES	('P0122', 'BEJO SUTEJO', 'DEMAM'),
	('P0123', 'BEJO SUTEJI', 'PILEK'),
	('P0124', 'BEJO SUTEJA', 'BATUK');
