USE databaseKelompok4;
DROP TABLE IF EXISTS ADMINISTRASI;


CREATE TABLE ADMINISTRASI(
  [ID_DAFTAR]    VARCHAR (30)   NOT NULL PRIMARY KEY,
  
  /*
  [ID_PASIEN]         VARCHAR (30)  FOREIGN KEY(),	
	[TANGGAL_PERIKSA]   DATE			    NOT NULL,
  [BIAYA]		          VARCHAR (10)	FOREIGN KEY(),
  [ID_RUANGAN]        VARCHAR (5)   NOT NULL FOREIGN KEY(),
  [ID_PEGAWAI]        VARCHAR (10)  FOREIGN KEY()
	*/
);
